import CenterHorizontalFull from "~/components/buildingBlocks/centerHorizontalFull";
import Text from "~/components/buildingBlocks/text";
import VStackFull from "~/components/buildingBlocks/vStackFull";
import HL from "./hl";
import Button from "~/components/buildingBlocks/button";
import { CloseIcon } from "styles";
import Box from "~/components/buildingBlocks/box";
import IconButton from "~/components/buildingBlocks/iconButton";
import CenterFull from "~/components/buildingBlocks/centerFull";

export default function ChatTermsOfServiceContent({
  onClick,
}: {
  onClick: () => void;
}) {
  const headingStyles = "text-[3.5vh] text-cyan-300 textShadow";

  return (
    <CenterFull>
      <Box className="p-[1vh]">
        <Box className="metallicEdgesMd">
          <VStackFull
            className={`p-[1vh] md:p-[2vh] bg-slate-900 bg-gradient-to-br from-indigo-700/40 via-fuchsia-700/40 to-violet-700/40 text-slate-100 text-[1.7vh] md:text-[1.9vh] border-970-md shadowBroadLooser h-full justify-between py-[1.5vh] relative`}
            align="items-start"
            gap="gap-[1vh] md:gap-[2vh]"
            style={{ maxHeight: "100svh" }}
          >
            <Box className="absolute top-[1vh] right-[1vh]">
              <IconButton
                type="smallNormal"
                icon={CloseIcon}
                onClick={onClick}
              />
            </Box>
            <VStackFull>
              <CenterHorizontalFull>
                <Text className={headingStyles}>Terms of Use</Text>
              </CenterHorizontalFull>
              <Text>
                1. <HL>Ownership of Data </HL>- The user retains ownership of
                the data they input into the chatbot (User Input) and the data
                generated by the chatbot in response to the User Input
                (Generated Data). The user assumes responsibility for the User
                Input and the Generated Data at the time it is generated.{" "}
              </Text>
              <Text>
                2. <HL>License to Darkviolet.ai</HL> - By using our chatbot, the
                user grants Darkviolet.ai a non-exclusive, worldwide,
                royalty-free, sublicensable, and transferable license to:{" "}
              </Text>
              <VStackFull className="px-[3vh]" align="items-start">
                <Text>
                  a - Use the User Input and Generated Data to display within
                  the user's session.
                </Text>{" "}
                <Text>
                  b - Store and use both the User Input and the Generated Data
                  to enhance our AI generation models in the future. This
                  includes the right to use this data for training, testing, and
                  improving our AI models.
                </Text>{" "}
              </VStackFull>
              <Text>
                3. <HL>Cookie Use</HL> - The user agrees to the use of cookies
                by Darkviolet.ai. These cookies are used to identify the user's
                session so that the chat conversation can be retrieved and
                continued at a later time. The user can manage their cookie
                preferences through their browser settings, but please note that
                disabling cookies may affect the functionality of the chatbot.
              </Text>
            </VStackFull>
            <CenterHorizontalFull>
              <Button
                buttonText="close"
                iconLeft={CloseIcon}
                onClick={onClick}
              />
            </CenterHorizontalFull>
          </VStackFull>
        </Box>
      </Box>
    </CenterFull>
  );
}
